name: rescan
description: An Flutter application for scanning product barcodes.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  firebase_core: ^2.14.0
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  go_router: ^9.0.0
  injectable: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.6
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/svg/

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf
        - asset: lib/assets/fonts/Roboto-Medium.ttf
          weight: 500

flutter_gen:
  output: lib/core/gen/
  integrations:
    flutter_svg: true
