// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv-ghxliefexPCKUu33VxVMgLYD2BGBX0',
    appId: '1:592626987215:web:71d222427cc678fe8987ba',
    messagingSenderId: '592626987215',
    projectId: 'doggo-317910',
    authDomain: 'doggo-317910.firebaseapp.com',
    storageBucket: 'doggo-317910.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqymk8cKnlG6s1nxkPqWJ5VVVGThV6trA',
    appId: '1:592626987215:android:697029a901d4600d8987ba',
    messagingSenderId: '592626987215',
    projectId: 'doggo-317910',
    storageBucket: 'doggo-317910.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGS35I6OwBFz8A_tF-BXnzc53f9g04n9c',
    appId: '1:592626987215:ios:3d37e87ede7d5b118987ba',
    messagingSenderId: '592626987215',
    projectId: 'doggo-317910',
    storageBucket: 'doggo-317910.appspot.com',
    iosClientId:
        '592626987215-542n04sb10kuh4klcpafbin896th359v.apps.googleusercontent.com',
    iosBundleId: 'com.example.canbe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGS35I6OwBFz8A_tF-BXnzc53f9g04n9c',
    appId: '1:592626987215:ios:f61845a60ba416ce8987ba',
    messagingSenderId: '592626987215',
    projectId: 'doggo-317910',
    storageBucket: 'doggo-317910.appspot.com',
    iosClientId:
        '592626987215-vqr26g0nc4gvubmdu7jkl2493tr8evpr.apps.googleusercontent.com',
    iosBundleId: 'com.example.canbe.RunnerTests',
  );
}
